# This is a basic workflow to help you get started with Actions

name: CI.tags

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Runs a single command using the runners shell
      - name: Compile js and sass
        run: yarn

      # Runs a set of commands using the runners shell
      - name: Build the assets
        run: yarn build

      # Runs a set of commands using the runners shell
      - name: Display branch name
        run: echo "tags/${GITHUB_REF_NAME}"

      - name: Set env.TAG_BRANCH
        run: echo "TAG_BRANCH=$(echo tags/${GITHUB_REF_NAME})" >> $GITHUB_ENV

      - name: Build static storybook
        run: yarn build-storybook && mv storybook-static ${GITHUB_REF_NAME}
      - name: Push static assets
        uses: dmnemec/copy_file_to_another_repo_action@3fe42250d47e0764da9de9939b151b09a26e5857
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'dist'
          destination_repo: 'FoodStandardsAgency/fsa-pattern-library-assets'
          destination_branch_create: ${{ env.TAG_BRANCH }}
          user_email: 'peterb@deeson.co.uk'
          user_name: 'Peter Berryman'
